/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachine;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Seipati Portia Matlomabe
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
      //table_update();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SelectItemPanel = new javax.swing.JPanel();
        PurchaseButton1 = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        CokeRadioButton = new javax.swing.JRadioButton();
        SmartiesRadioButton = new javax.swing.JRadioButton();
        IceCreamRadioButton = new javax.swing.JRadioButton();
        EnergizerRadioButton = new javax.swing.JRadioButton();
        CoffeRadioButton = new javax.swing.JRadioButton();
        ChocMintRadioButton = new javax.swing.JRadioButton();
        InsertMoneyLabel = new javax.swing.JLabel();
        ChangeLabel = new javax.swing.JLabel();
        InsertMoneyTextField = new javax.swing.JTextField();
        ChangeTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSales = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("SBSA VENDING MACHINE");

        SelectItemPanel.setBackground(new java.awt.Color(204, 204, 255));
        SelectItemPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECT ITEM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        PurchaseButton1.setBackground(new java.awt.Color(51, 51, 255));
        PurchaseButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PurchaseButton1.setForeground(new java.awt.Color(0, 0, 255));
        PurchaseButton1.setText("PURCHASE");
        PurchaseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseButton1ActionPerformed(evt);
            }
        });

        ClearButton.setBackground(new java.awt.Color(51, 51, 255));
        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(0, 0, 255));
        ClearButton.setText("CLEAR");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(0, 0, 255));
        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(51, 51, 255));
        CancelButton.setText("CANCEL");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        RefreshButton.setBackground(new java.awt.Color(0, 51, 255));
        RefreshButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RefreshButton.setForeground(new java.awt.Color(0, 0, 255));
        RefreshButton.setText("REFRESH");

        SaveButton.setBackground(new java.awt.Color(51, 51, 255));
        SaveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(0, 0, 255));
        SaveButton.setText("SAVE");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CokeRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CokeRadioButton.setForeground(new java.awt.Color(0, 0, 255));
        CokeRadioButton.setText("Coke R20.00");
        CokeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CokeRadioButtonActionPerformed(evt);
            }
        });

        SmartiesRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        SmartiesRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SmartiesRadioButton.setForeground(new java.awt.Color(0, 0, 255));
        SmartiesRadioButton.setText("Smarties R10.00");
        SmartiesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmartiesRadioButtonActionPerformed(evt);
            }
        });

        IceCreamRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IceCreamRadioButton.setForeground(new java.awt.Color(0, 0, 255));
        IceCreamRadioButton.setText("Ice Cream R 15.00");
        IceCreamRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IceCreamRadioButtonActionPerformed(evt);
            }
        });

        EnergizerRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnergizerRadioButton.setForeground(new java.awt.Color(0, 0, 255));
        EnergizerRadioButton.setText("Energizer R25.00");
        EnergizerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnergizerRadioButtonActionPerformed(evt);
            }
        });

        CoffeRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CoffeRadioButton.setForeground(new java.awt.Color(0, 0, 255));
        CoffeRadioButton.setText("Coffe R8.00");
        CoffeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoffeRadioButtonActionPerformed(evt);
            }
        });

        ChocMintRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChocMintRadioButton.setForeground(new java.awt.Color(0, 0, 204));
        ChocMintRadioButton.setText("Choc Mint Cup Cake R18.00");

        InsertMoneyLabel.setBackground(new java.awt.Color(0, 0, 255));
        InsertMoneyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InsertMoneyLabel.setForeground(new java.awt.Color(0, 0, 255));
        InsertMoneyLabel.setText("INSERT MONEY :");

        ChangeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChangeLabel.setForeground(new java.awt.Color(0, 0, 255));
        ChangeLabel.setText("CHANGE :");

        jTableSales.setForeground(new java.awt.Color(0, 0, 204));
        jTableSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableSales);

        javax.swing.GroupLayout SelectItemPanelLayout = new javax.swing.GroupLayout(SelectItemPanel);
        SelectItemPanel.setLayout(SelectItemPanelLayout);
        SelectItemPanelLayout.setHorizontalGroup(
            SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectItemPanelLayout.createSequentialGroup()
                .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(SelectItemPanelLayout.createSequentialGroup()
                            .addComponent(ChangeLabel)
                            .addGap(68, 68, 68)
                            .addComponent(ChangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SelectItemPanelLayout.createSequentialGroup()
                            .addComponent(InsertMoneyLabel)
                            .addGap(18, 18, 18)
                            .addComponent(InsertMoneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SelectItemPanelLayout.createSequentialGroup()
                        .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectItemPanelLayout.createSequentialGroup()
                                    .addComponent(CokeRadioButton)
                                    .addGap(34, 34, 34))
                                .addGroup(SelectItemPanelLayout.createSequentialGroup()
                                    .addComponent(SmartiesRadioButton)
                                    .addGap(10, 10, 10)))
                            .addGroup(SelectItemPanelLayout.createSequentialGroup()
                                .addComponent(PurchaseButton1)
                                .addGap(38, 38, 38)))
                        .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectItemPanelLayout.createSequentialGroup()
                                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SelectItemPanelLayout.createSequentialGroup()
                                .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EnergizerRadioButton)
                                    .addComponent(IceCreamRadioButton))
                                .addGap(45, 45, 45)
                                .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CoffeRadioButton)
                                    .addComponent(ChocMintRadioButton)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        SelectItemPanelLayout.setVerticalGroup(
            SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertMoneyLabel)
                    .addComponent(InsertMoneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangeLabel)
                    .addComponent(ChangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CokeRadioButton)
                    .addComponent(IceCreamRadioButton)
                    .addComponent(CoffeRadioButton))
                .addGap(31, 31, 31)
                .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SmartiesRadioButton)
                    .addComponent(EnergizerRadioButton)
                    .addComponent(ChocMintRadioButton))
                .addGap(34, 34, 34)
                .addGroup(SelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PurchaseButton1)
                    .addComponent(ClearButton)
                    .addComponent(CancelButton)
                    .addComponent(RefreshButton)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SelectItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelectItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PurchaseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseButton1ActionPerformed
        // This is for our purchase if we have enough money
        
        double money = 0;
        money = Double.parseDouble(InsertMoneyTextField.getText());
        
        if(ChocMintRadioButton.isSelected())
        {
            money = money - 18.00;
        
        }
        else if(CokeRadioButton.isSelected())
        {
            money = money - 20.00;
        }
        else if(IceCreamRadioButton.isSelected())
        {
            money = money - 15.00;
        }
        else if(CoffeRadioButton.isSelected())
        {
            money = money - 8.00;
        }
        else if(SmartiesRadioButton.isSelected())
        {
            money = money - 10.00;
        }
        else if(EnergizerRadioButton.isSelected())
        {
            money = money - 25.00;
        }
        
        if(money < 0)
        {
            JOptionPane.showMessageDialog(rootPane, " Sorry you do not have enough money ");
        }
        else
        {
            ChangeTextField.setText(Double.toString(money));
        }
    }//GEN-LAST:event_PurchaseButton1ActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // Cancel Selections
        
        System.exit(0);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // Clears all selections and text fields
        
       CokeRadioButton.setSelected(false);
       CoffeRadioButton.setSelected(false);
       EnergizerRadioButton.setSelected(false);
       IceCreamRadioButton.setSelected(false);
       SmartiesRadioButton.setSelected(false);
       ChocMintRadioButton.setSelected(false);
       InsertMoneyTextField.setText(" ");
       ChangeTextField.setText(" ");
       
        
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void CokeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CokeRadioButtonActionPerformed
        // Changing RadioButtons to only select one
        
        if(CokeRadioButton.isSelected())
        {
            CokeRadioButton.setText("Coke is R20.00");
            CoffeRadioButton.setSelected(false);
            EnergizerRadioButton.setSelected(false);
            IceCreamRadioButton.setSelected(false);
            SmartiesRadioButton.setSelected(false);
            ChocMintRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_CokeRadioButtonActionPerformed

    private void IceCreamRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IceCreamRadioButtonActionPerformed
        // Changing RadioButtons to only select one
        if(IceCreamRadioButton.isSelected())
        {
        IceCreamRadioButton.setText("Ice Cream is R15.00");
       CokeRadioButton.setSelected(false);
       CoffeRadioButton.setSelected(false);
       EnergizerRadioButton.setSelected(false);
       SmartiesRadioButton.setSelected(false);
       ChocMintRadioButton.setSelected(false);
       CokeRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_IceCreamRadioButtonActionPerformed

    private void CoffeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoffeRadioButtonActionPerformed
        // Changing RadioButtons to only select one
        
          if(CoffeRadioButton.isSelected())
        {
      CoffeRadioButton.setText("Coffee is R8.00");
       CokeRadioButton.setSelected(false);
       EnergizerRadioButton.setSelected(false);
       SmartiesRadioButton.setSelected(false);
       ChocMintRadioButton.setSelected(false);
       IceCreamRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_CoffeRadioButtonActionPerformed

    private void SmartiesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmartiesRadioButtonActionPerformed
        // Changing RadioButtons to only select one
        
           if(SmartiesRadioButton.isSelected())
        {
         SmartiesRadioButton.setText("Smarties is R10.00");
       CokeRadioButton.setSelected(false);
       EnergizerRadioButton.setSelected(false);
       ChocMintRadioButton.setSelected(false);
       CoffeRadioButton.setSelected(false);
       IceCreamRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_SmartiesRadioButtonActionPerformed

    private void EnergizerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnergizerRadioButtonActionPerformed
       
        // Changing RadioButtons to only select one
           if(EnergizerRadioButton.isSelected())
        {
           EnergizerRadioButton.setText("Energizer is R25.00");
       CokeRadioButton.setSelected(false);
       ChocMintRadioButton.setSelected(false);
       CoffeRadioButton.setSelected(false);
       IceCreamRadioButton.setSelected(false);
       SmartiesRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_EnergizerRadioButtonActionPerformed
  Connection con1;
       PreparedStatement insert;
       
       private void table_update()
       {
           int c;
           try {
            Class.forName("com.mysql.jdbc.Driver");
            //table_update();
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/vendingmachinedb","root","");
            insert = con1.prepareStatement("Select * from sales ");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = rs.getMetaData(); 
            c = rss.getColumnCount();
            
            DefaultTableModel model = ( DefaultTableModel)jTableSales.getModel();
            model.setRowCount(0);
            
            while(rs.next())
            {
                Vector v = new Vector();
                
                for(int i = 1; i <=0; i++)
                {
                    v.add(rs.getString("Id"));
                    v.add(rs.getString("ItemName"));
                    v.add(rs.getString("Price"));
                    v.add(rs.getString("MoneyReturned"));
                    
                }
                model.addRow(v);
            }
            
            
            
            JOptionPane.showMessageDialog(this, " Record Added " );
            
            CokeRadioButton.setText(" ");
            ChocMintRadioButton.setText(" ");
           CoffeRadioButton.setText(" ");
            IceCreamRadioButton.setText(" ");
           SmartiesRadioButton.setText(" ");
           EnergizerRadioButton.setText(" ");
             InsertMoneyTextField.setText(" ");
           ChangeTextField.setText(" ");
            InsertMoneyTextField.requestFocus();
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       }
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // Shows the item that have been bought
       String ItemName = CokeRadioButton.getText();
       String name = ChocMintRadioButton.getText();
       String aa =CoffeRadioButton.getText();
       String bb =IceCreamRadioButton.getText();
       String cc =SmartiesRadioButton.getText();
       String dd = EnergizerRadioButton.getText();
      String Price = InsertMoneyTextField.getText();
       String MoneyReturned = ChangeTextField.getText();
       
       
       
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/vendingmachinedb","root","");
            insert = con1.prepareStatement("Insert into sales(ItemName,Price,MoneyReturned)values(???)");
            insert.setString(1, ItemName);
            insert.setString(2, Price);
            insert.setString(3, MoneyReturned);
            insert.executeUpdate();
             table_update();
            
            JOptionPane.showMessageDialog(this, " Record Added " );
            
            CokeRadioButton.setText(" ");
            ChocMintRadioButton.setText(" ");
            CoffeRadioButton.setText(" ");
            IceCreamRadioButton.setText(" ");
            SmartiesRadioButton.setText(" ");
            EnergizerRadioButton.setText(" ");
             InsertMoneyTextField.setText(" ");
            ChangeTextField.setText(" ");
            InsertMoneyTextField.requestFocus();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            
    }//GEN-LAST:event_SaveButtonActionPerformed
private void ChocMintRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO if(ChocMintRadioButton.isSelected())
        {
            ChocMintRadioButton.setText("Choco Mint is R18.00");
            CokeRadioButton.setSelected(false);
            EnergizerRadioButton.setSelected(false);
            CoffeRadioButton.setSelected(false);
            IceCreamRadioButton.setSelected(false);
            SmartiesRadioButton.setSelected(false);
        }
    }                 
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel ChangeLabel;
    private javax.swing.JTextField ChangeTextField;
    private javax.swing.JRadioButton ChocMintRadioButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JRadioButton CoffeRadioButton;
    private javax.swing.JRadioButton CokeRadioButton;
    private javax.swing.JRadioButton EnergizerRadioButton;
    private javax.swing.JRadioButton IceCreamRadioButton;
    private javax.swing.JLabel InsertMoneyLabel;
    private javax.swing.JTextField InsertMoneyTextField;
    private javax.swing.JButton PurchaseButton1;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JPanel SelectItemPanel;
    private javax.swing.JRadioButton SmartiesRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableSales;
    // End of variables declaration//GEN-END:variables
}
